### ISSUE TITLE
Hook PHP objects magic calls

### ISSUE THREAD

**Issue by epinna** [sciactive/hookphp#2]
Hello,

Have you thought to allow to hook magic calls too? For example 

```
\SciActive\Hook::addCallback('Test->__toString', -2, function(&$arguments, $name, &$object, &$function, &$data){
});
```

Would be triggered by `print($obj);`. Same for constructor, setters and getters, etc.

**Comment by hperrin** [comment]
I haven't, but yeah, I could definitely do that.

**Comment by hperrin** [comment]
Didn't mean to close that.

**Comment by epinna** [comment]
Cool, looking forward for it.

**Comment by hperrin** [comment]
I've added the ability to hook `jsonSerialize`.
